[package]
name = "chinese-chars-to-json"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "./src/main.rs"
name = "china"

[dependencies]
csv = "1.1.6"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"